version: "3.7"
services:
    php-fpm:
        build:
            context: ./docker/php-fpm
        depends_on:
            - mysql
        container_name: todo_list-php_fpm
        restart: unless-stopped
        tty: true
        environment:
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - backend
    nginx:
        build:
            context: ./docker/nginx
        depends_on:
            - php-fpm
        container_name: todo_list-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/log:/var/log/nginx
        networks:
            - backend
    mysql:
        build:
            context: ./docker/mysql
        container_name: todo_list-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - backend
networks:
    backend:
        driver: bridge
