version: "3.7"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:7.4-fpm
        container_name: todo_list-php_fpm
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - backend
    nginx:
        image: nginx:1.18-alpine
        container_name: todo_list-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        environment:
            SERVICE_NAME: nginx
            SERVICE_TAGS: dev
        extra_hosts:
            - "localhost:127.0.0.1"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        networks:
            - backend
    mysql:
        image: mysql:8.0
        container_name: todo_list-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: todo_list
            MYSQL_USER: todo_list
            MYSQL_PASSWORD: todo_list
            MYSQL_ROOT_PASSWORD: root
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        networks:
            - backend
networks:
    backend:
        driver: bridge
